### ISSUE TITLE
Initiation from tox side

### ISSUE THREAD

**Issue by erkinalp** [Sorunome/mx-puppet-tox#3]
This bridge can only be initiated from matrix side as it stands. The bridge should be as symmetrical as possible, as protocols have different security properties.

**Comment by Sorunome** [comment]
what do you mean by initiating? since tox doesn't have multidevice this tox bridge is essentially just matrix-as-tox-client

**Comment by erkinalp** [comment]
What I meant is you should also provide tox-as-matrix-device capability.

**Comment by Sorunome** [comment]
do you mean that you use tox as your matrix client?

**Comment by erkinalp** [comment]
That I should be able to do so.

**Comment by Sorunome** [comment]
that is way out of scope for this project.
